### ISSUE TITLE
Exception needs to included

### ISSUE THREAD

**Issue by AlexStansfield** [coreydoughty/FpdfBundle#2]
As you're using namespaces this exception class needs to be fully qualified or it expects there to be an Exception class in your namespace.

https://github.com/coreydoughty/Fpdf/blob/474ae46fe72afbd5c5b67f22312a0e948b018c62/src/Fpdf/Fpdf.php#L259

Either prefix with a `\` or add `use Exception;` at the top of the file

**Comment by coreydoughty** [comment]
Thanks. Adjusted. I use to have a few adjustments like this but recently changed the source to be as close to the original as possible. I agree that this is a proper adjustment.

**Comment by glashio** [comment]
Version: 1.82
vendor/fpdf/fpdf/src/Fpdf/Fpdf.php:272`		throw new Exception('FPDF error: '.$msg);`
Still not changed :)
