### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by wblessen** [coreydoughty/FpdfBundle#22]
Do you have an example, of how to add extensions?

I am trying to create a PDF/A-3 compatible PDF?

Is it possible to load

http://www.fpdf.org/en/script/script103.php

**Comment by coreydoughty** [comment]
Not tested but you should be able to use that script with adding something like "use Fpdf\Fpdf;" on the top of the file instead of the "require('fpdf.php');" line. You'd also need to change "extends FPDF" to "extends Fpdf"
