### ISSUE TITLE
Latest release points to outdated version

### ISSUE THREAD

**Issue by strlns** [coreydoughty/FpdfBundle#6]
Would you mind tagging the latest commit?

Currently, if not using `dev-master`, packagist points composer to the latest tagged revision a8eb66ba, which contains the call to the non-qualified Exception constructor.

Thank you for your work!

**Comment by coreydoughty** [comment]
Sorry for the delay on this. I think this would be fixed with the 1.83 update and the 1.83.1 tagging.
