### ISSUE TITLE
License for fonts?

### ISSUE THREAD

**Issue by hrieke** [coreydoughty/FpdfBundle#7]
[This issue is also at: http://www.fpdf.org/phorum/read.php?f=1&i=61551&t=61551]
Really hate to be *that guy*, but it's important.

Can you explain where the fonts originated from and under what license they are being distributed under?

For example, I see using Exiftool, that the Palantino Lino fonts contain a copyright notice from Heidelberger Druckmaschinen AG and secondary notice from Microsoft.
Furthermore, they [edit: Palantino Lino] do not appear in the Core fonts for the Web, as published by Microsoft  (see https://en.wikipedia.org/wiki/Core_fonts_for_the_Web for details).

There are excellent Open Source / Permissively Licensed fonts galore, perhaps it's time to retire these with unknown providence?

Files in question:
courier.php
courierb.php
courierbi.php
courieri.php
helvetica.php
helveticab.php
helveticabi.php
helveticai.php
palatinolinotypeitalic.afm
palatinolinotypeitalic.php
palatinolinotypeitalic.t1a
palatinolinotypeitalic.ttf
palatinolinotypeitalic.ufm
palatinolinotypeitalic.z
symbol.php
times.php
timesb.php
timesbi.php
timesi.php
zapfdingbats.php

**Comment by hrieke** [comment]
Also forgot to mention:
calligra.php
calligra.ttf
calligra.z

Which appears to be from:
~https://www.ctan.org/tex-archive/fonts/calligra/~

Update from Olivier at http://www.fpdf.org/phorum/read.php?f=1&i=61551&t=61551, states that Calligra came from https://www.abstractfonts.com/font/52
and has an Unknown License.

**Comment by coreydoughty** [comment]
Fonts were removed that were put in by accident. I set the font folder to be exactly equal to the Fpdf original folder. Thanks for catching this and thanks for the suggestion of the open fonts. However my goal for this repo is to be as close to the original Fpdf source as possible. I really only changed a few things for it to work with Composer/Packagist.
